# Generated by Django 2.1.1 on 2018-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinfo',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America'), ('AN', 'Antartica')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
