# Generated by Django 2.1.2 on 2018-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Word on page', max_length=255)),
                ('isAlnum', models.BooleanField()),
                ('url', models.URLField(help_text='URL with word')),
                ('count', models.IntegerField(help_text='Number of times word appears on page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wordindex',
            unique_together={('word', 'url')},
        ),
    ]
