# Generated by Django 2.1.2 on 2018-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordindex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL with word', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(help_text='Number of times word appears cumulatively')),
                ('isAlnum', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='wordindex',
            name='count',
            field=models.IntegerField(help_text='Number of times word appears on this page'),
        ),
        migrations.AlterUniqueTogether(
            name='wordindex',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wordindex',
            name='isAlnum',
        ),
        migrations.RemoveField(
            model_name='wordindex',
            name='url',
        ),
        migrations.RemoveField(
            model_name='wordindex',
            name='word',
        ),
    ]
