# Generated by Django 2.1.1 on 2018-09-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('case_id', models.IntegerField()),
                ('assessment_id', models.IntegerField()),
                ('agency_text', models.CharField(max_length=255)),
                ('supervision_level', models.IntegerField()),
                ('recidivism_score_raw', models.FloatField()),
                ('recidivism_score', models.IntegerField()),
                ('violence_score_raw', models.FloatField()),
                ('violence_score', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('ethnicity', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('legal_status', models.CharField(max_length=50)),
                ('custody_status', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='inmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compas.Inmate'),
        ),
    ]
