# Generated by Django 2.1.1 on 2018-09-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='fail_to_appear_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='fail_to_appear_score_raw',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
