# Generated by Django 2.1.1 on 2018-09-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compas', '0002_auto_20180928_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='reason',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='fail_to_appear_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='fail_to_appear_score_raw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='recidivism_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='recidivism_score_raw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='violence_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='violence_score_raw',
            field=models.FloatField(null=True),
        ),
    ]
