# Generated by Django 2.1.2 on 2018-10-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compas', '0003_auto_20180929_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('copy', 'Copy')], max_length=4),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='ethnicity',
            field=models.CharField(choices=[('african-american', 'African American'), ('asian', 'Asian'), ('caucasian', 'Caucasian'), ('hispanic', 'Hispanic'), ('native-american', 'Native American'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish')], max_length=7),
        ),
    ]
