# Generated by Django 2.1.1 on 2018-10-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compas', '0004_auto_20181005_1924'),
        ('compas', '0004_auto_20180929_1032'),
    ]

    operations = [
    ]
