# Generated by Django 2.1.1 on 2018-09-25 00:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wiki_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('bag_size', models.IntegerField()),
                ('bag', django.contrib.postgres.fields.jsonb.JSONField()),
                ('header_bag_size', models.IntegerField()),
                ('header_bag', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
