# Generated by Django 2.1.1 on 2018-09-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikibags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='page',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
